# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfa0a35f9910570d542e969b613a87e9a27a69534b85eb1ce98af92e192b75e3c81010ce34dc6335867499e2b7ee5ec9055210978edbd661dc8cf76fd9b5dabc

test:
  secret_key_base: ccae6778e0a99037f67eec448d8d761a86eaf8bb815a2c90c8174010611e7dedac9015852a227384cd655de68b382dcffc79cedeea710b2608f34012b2f9f0f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
